// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using InterviewCRUD_NetCore.Repository.Entities;

#nullable disable

namespace InterviewCRUD_NetCore.Repository.Context
{
    public partial class CourseselectionContext : DbContext
    {
        public CourseselectionContext(DbContextOptions<CourseselectionContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseSelect> CourseSelect { get; set; }
        public virtual DbSet<Student> Student { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Course>(entity =>
            {
                entity.HasKey(e => e.Number)
                    .HasName("PK__Course__78A1A19C8547145C");

                entity.Property(e => e.Number)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Name).HasMaxLength(20);

                entity.Property(e => e.Place).HasMaxLength(20);

                entity.Property(e => e.TeacherName).HasMaxLength(20);
            });

            modelBuilder.Entity<CourseSelect>(entity =>
            {
                entity.Property(e => e.CourseNumber)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.StudentNumber)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.HasOne(d => d.CourseNumberNavigation)
                    .WithMany(p => p.CourseSelect)
                    .HasForeignKey(d => d.CourseNumber)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CourseSel__Cours__286302EC");

                entity.HasOne(d => d.StudentNumberNavigation)
                    .WithMany(p => p.CourseSelect)
                    .HasForeignKey(d => d.StudentNumber)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CourseSel__Stude__276EDEB3");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.HasKey(e => e.Number)
                    .HasName("PK__Student__78A1A19C16F2FCC0");

                entity.Property(e => e.Number)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Birthday).HasColumnType("datetime");

                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.Name).HasMaxLength(20);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}