// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InterviewCRUD_NetCore.Repository.Entities
{
    public partial class CourseSelect
    {
        public int Id { get; set; }
        public string StudentNumber { get; set; }
        public string CourseNumber { get; set; }

        public virtual Course CourseNumberNavigation { get; set; }
        public virtual Student StudentNumberNavigation { get; set; }
    }
}