// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InterviewCRUD_NetCore.Repository.Entities
{
    public partial class Course
    {
        public Course()
        {
            CourseSelect = new HashSet<CourseSelect>();
        }

        public string Number { get; set; }
        public string Name { get; set; }
        public int? Credit { get; set; }
        public string Place { get; set; }
        public string TeacherName { get; set; }

        public virtual ICollection<CourseSelect> CourseSelect { get; set; }
    }
}