// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace InterviewCRUD_NetCore.Repository.Entities
{
    public partial class Student
    {
        public Student()
        {
            CourseSelect = new HashSet<CourseSelect>();
        }

        public string Number { get; set; }
        public string Name { get; set; }
        public DateTime? Birthday { get; set; }
        public string Email { get; set; }

        public virtual ICollection<CourseSelect> CourseSelect { get; set; }
    }
}